#!/usr/bin/perl -wT

# Notes on chroot setup
# apt-get install dchroot debootstrap
# mkdir /opt/atscc-jail
# adduser atscc
#
# Add the following to /etc/schroot.conf
#  [natty]
#  description=Ubuntu Natty
#  location=/opt/atscc-jail
#  priority=3
#  users=atscc
#  groups=sbuild
#  root-groups=root
# 
# sudo debootstrap --variant=buildd --arch amd64 natty /opt/atscc-jail http://mirror.anl.gov/pub/ubuntu/
# cp -r /opt/ats-0.2.7 /opt/atscc-jail/opt/ats-0.2.7
# sudo chmod -R o-rw /tmp
# cp lib/safe-exec.c /opt/atscc-jail/opt/

$typecheck = "";

if($ARGV[0] && !($ARGV[0] =~ m#^(\-tc)$# && ($typecheck = $1) ) ) {
  exit;
}

use POSIX;
use BSD::Resource;
use String::Random;
use IO::Handle;

$chroot_jail = "/opt/atscc-jail-x86";

$rand = new String::Random;
$file_to_open = $rand->randpattern("CnccCcCCncnCcnncCcnCnCcCnCnC");

setrlimit(RLIMIT_NPROC,12,12);
setrlimit(RLIMIT_CPU,3,3);
setrlimit(RLIMIT_CORE,0,0);
setrlimit(RLIMIT_LOCKS,0,0);
setrlimit(RLIMIT_NOFILE,25,25);
setrlimit(RLIMIT_OFILE,25,25);
setrlimit(RLIMIT_OPEN_MAX,25,25);

($_,$_,$uid,$gid) = getpwnam("nobody")
        or die "atscc not in passwd file";

#print $typecheck."\n";
#print $id."\n";

if($gid == 0 || $uid == 0) { #Oh my god, how did you become root?!
  exit;
}

$source = "";

while($line = <STDIN>) {
  if($line =~ m#(.*)#) {
    $source .= $1."\n";
  }
}

@files = ("$file_to_open.dats",$file_to_open."_dats.c", $file_to_open);

foreach $fn (@files) {
	open(SRC,"+>","$chroot_jail/tmp/$fn") or die;
	close(SRC);
}

chdir("$chroot_jail/tmp");

chown $uid, $gid, @files;

#Put the process in jail
chdir($chroot_jail);
chroot($chroot_jail);
setuid($uid);
setgid($gid);

$ENV{'PATH'} = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin";
$ENV{'ATSHOME'} = "/opt/ats-0.2.7";

$SIG{ALRM} = sub { kill 9, getpid() };

alarm 3; #Probably redundant...

open(SRC, "+>", "/tmp/".$file_to_open.".dats") or die "Cannot open temporary file.";
print SRC $source;
close(SRC);

chdir("/tmp"); #ATS needs to generate code in the pwd.
$comp_passed = system("/opt/ats-0.2.7/bin/atscc $typecheck -o /tmp/$file_to_open /tmp/$file_to_open.dats") == 0;

if($comp_passed && !$typecheck) {
    system "/opt/safe-exec /tmp/$file_to_open";
}

unlink @files;
