#!/bin/bash
#Add to /etc/init.d
set -e

USER=ats
APP_ROOT=/home/ats/lxrats/current
PID=$APP_ROOT/tmp/pids/unicorn.lxrats.pid
CMD="cd $APP_ROOT; bin/unicorn -c config/unicorn.rb -E none -D"
action="$1"
set -u

old_pid="$PID.oldbin"

cd $APP_ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $old_pid && kill -$1 `cat $old_pid`
}

case $action in
start)
  sig 0 && echo >&2 "Already running" && exit 0
  su -s /bin/bash $USER -c "$CMD" -l
  ;;
stop)
  sig QUIT && rm $PID && exit 0
  echo >&2 "Not running"
  ;;
restart|reload)
  sig USR2 && echo reloaded OK && exit 0
  echo >&2 "Couldn't reload, starting '$CMD' instead"
  su ats -l -c "$CMD"
  ;;
*)
  echo >&2 "Usage: $0 <start|stop|restart|reload>"
  exit 1
  ;;
esac
